---
- name: Local Group creation
  win_group:
    name: "{{ local_group_name }}"
    force: true
    gid: "{{ gid }}"
  register: result

- name: get local group creation details
  debug: 
    msg: "result  is {{ result }}"
