---
- name: Add or update registry path MyCompany, with entry 'hello', and containing 'world'
  win_regedit:
    path: "{{ item.value.path }}"
    name: "{{ item.key }}"
    data: "{{ item.value.data }}"
  loop: "{{ lookup('dict', registry) }}"
    
